/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuplasPPD;

import java.awt.BorderLayout;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;


/**
 *
 * @author user
 */
public class Home extends javax.swing.JFrame {

     Controller controller = new Controller();
     DefaultListModel listaAmbModel = new DefaultListModel();
     DefaultListModel listaUserModel = new DefaultListModel();
     DefaultListModel listaDispModel = new DefaultListModel();
   
    public Home() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        btnCriarAmbiente = new javax.swing.JButton();
        btnCriarUsuario = new javax.swing.JButton();
        btnCriarDispositivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAmb = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaUser = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaDisp = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        btnCriarAmbiente.setText("Criar Ambiente");
        btnCriarAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarAmbienteActionPerformed(evt);
            }
        });

        btnCriarUsuario.setText(" Criar Usuário");
        btnCriarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarUsuarioActionPerformed(evt);
            }
        });

        btnCriarDispositivo.setText("Criar Dispositivo");
        btnCriarDispositivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarDispositivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCriarAmbiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCriarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCriarDispositivo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btnCriarAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCriarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCriarDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listaAmb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listaAmb.setMaximumSize(new java.awt.Dimension(73, 135));
        listaAmb.setMinimumSize(new java.awt.Dimension(73, 135));
        listaAmb.setPreferredSize(new java.awt.Dimension(73, 135));
        listaAmb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaAmbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaAmb);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ambientes");

        listaUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listaUser.setMaximumSize(new java.awt.Dimension(73, 135));
        listaUser.setMinimumSize(new java.awt.Dimension(73, 135));
        listaUser.setPreferredSize(new java.awt.Dimension(73, 135));
        listaUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaUser);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Usuarios");

        listaDisp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listaDisp.setMaximumSize(new java.awt.Dimension(73, 135));
        listaDisp.setMinimumSize(new java.awt.Dimension(73, 135));
        listaDisp.setPreferredSize(new java.awt.Dimension(73, 135));
        listaDisp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDispMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaDisp);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Dispositivos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(54, 54, 54)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Funcao para adicionar os itens(amb, user, disp) na lista do modelo
    private void addItemToList(String item, DefaultListModel listModel, JList list){
        list.setModel(listModel);
        listModel.addElement(item);
    }
    
    //envia as informações de usuario para a tela de bate papo
    public String[] mostrarLista() {
        String elementos = controller.listarUsuarioBatePapo(listaUser.getSelectedValue());
        return elementos.split(", ");
    }
    
    public String usuarioConectade(){
        String usuarioConectade = listaUser.getSelectedValue();
        return usuarioConectade;
    }

    public JList<String> getUsuarioList() {
        return listaUser;
    }
    
    /*
    * Funcoes para adicionar amb, user e disp 
    */
    private void btnCriarAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarAmbienteActionPerformed
        // Botao adiciona ambiente na lista de ambientes
        addItemToList(controller.criarAmbiente(), listaAmbModel, listaAmb );
    }//GEN-LAST:event_btnCriarAmbienteActionPerformed

    private void btnCriarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarUsuarioActionPerformed
        // Botao adiciona usuario na lista de usuario
        addItemToList(controller.criarUsuario(), listaUserModel, listaUser);
    }//GEN-LAST:event_btnCriarUsuarioActionPerformed

    private void btnCriarDispositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarDispositivoActionPerformed
        // TODO add your handling code here:
        addItemToList(controller.criarDispositivo(), listaDispModel, listaDisp);
    }//GEN-LAST:event_btnCriarDispositivoActionPerformed

    
    /**
     * Funcoes para as acoes do click do mouse
     */

    private void listaAmbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaAmbMouseClicked
        
        
// Crie um painel personalizado contendo a mensagem e os botões
        Object[] opcoes = {"Excluir Ambiente", "Cancelar"};

        // Mostre a caixa de diálogo
        int escolha = JOptionPane.showOptionDialog(
                null, 
                controller.listarDispositivo(listaAmb.getSelectedValue()) + controller.listarUsuario(listaAmb.getSelectedValue()), "Informações do " + listaAmb.getSelectedValue(), 
                JOptionPane.INFORMATION_MESSAGE, 
                JOptionPane.PLAIN_MESSAGE, 
                null, 
                opcoes, opcoes[0]);

        //Trata a opção que o usuario escolheu
        if (escolha == 0) {

            if (controller.contadorDispositivos(listaAmb.getSelectedValue()) == 0) {
                controller.excluirAmbiente(listaAmb.getSelectedValue());

                //atualizar a lista
                int index = listaAmb.getSelectedIndex();
                listaAmbModel.removeElementAt(index);
            } else {
                //Warning
                JLabel lblMessage = new JLabel("Antes de destruir o ambiente, remova todos os dispositivos e usuários.");
                Object[] texts = {lblMessage};
                JOptionPane.showMessageDialog(null, texts);
            }

        }
    }//GEN-LAST:event_listaAmbMouseClicked

    private void listaUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaUserMouseClicked
        // Crie um JTextField
        JTextField txtAmb1 = new JTextField("amb");

        // Crie um painel personalizado contendo a mensagem, o JTextField e os botões
        Object[] opcoes = {"Deletar Usuário", "Mover Usuário", "Iniciar Bate Papo", "Cancelar"};
        JPanel panel = new JPanel(new BorderLayout());
        panel.add(new JLabel("Escolha um ambiente:"), BorderLayout.NORTH);
        panel.add(txtAmb1, BorderLayout.CENTER);

        // Mostre a caixa de diálogo
        int escolha = JOptionPane.showOptionDialog(
                null, 
                panel, "Usuario: " + listaUser.getSelectedValue(), 
                JOptionPane.DEFAULT_OPTION, 
                JOptionPane.PLAIN_MESSAGE, 
                null, 
                opcoes, opcoes[2]);

         //Trata a opção que o usuario escolheu
         switch (escolha) {
             case 0:
                 controller.excluirDispositivo(listaDisp.getSelectedValue());
                 //atualizar a lista
                 int index = listaUser.getSelectedIndex();
                 listaUserModel.removeElementAt(index);
                 break;
             case 1:
                 controller.moverUsuario(listaUser.getSelectedValue(), txtAmb1.getText());
                 break;
             case 2:
                 Chat novoBatePapo = new Chat();
                 novoBatePapo.setUsuarioConectado(listaUser.getSelectedValue());
                 novoBatePapo.setAmbNome(controller.ambUsuarioBatePapo(listaUser.getSelectedValue()));
                 novoBatePapo.setVisible(true);
                 break;
             case 3:
                 break;
             default:
                 break;
         }
    }//GEN-LAST:event_listaUserMouseClicked

    private void listaDispMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDispMouseClicked
        // Crie um JTextField
        JTextField txtAmb = new JTextField("amb");

        // Crie um painel personalizado contendo a mensagem, o JTextField e os botões
        Object[] opcoes = {"Deletar Dispositivo", "Mover Dispositivo", "Cancelar"};
        JPanel panel = new JPanel(new BorderLayout());
        panel.add(new JLabel("Escolha um ambiente:"), BorderLayout.NORTH);
        panel.add(txtAmb, BorderLayout.CENTER);

        // Mostre a caixa de diálogo
        int escolha = JOptionPane.showOptionDialog(
                null, 
                panel, "Dispositivo: " + listaDisp.getSelectedValue(), 
                JOptionPane.DEFAULT_OPTION, 
                JOptionPane.PLAIN_MESSAGE, 
                null, 
                opcoes, opcoes[1]);

         //Trata a opção que o usuario escolheu
         switch (escolha) {
             case 0:
                 controller.excluirDispositivo(listaDisp.getSelectedValue());
                 //atualizar a lista
                 int index = listaDisp.getSelectedIndex();
                 listaDispModel.removeElementAt(index);
                 break;
             case 1:
                 controller.moverDispositivo(listaDisp.getSelectedValue(), txtAmb.getText());
                 break;
             case 2:
                 break;
             default:
                 break;
         }
    }//GEN-LAST:event_listaDispMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarAmbiente;
    private javax.swing.JButton btnCriarDispositivo;
    private javax.swing.JButton btnCriarUsuario;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaAmb;
    private javax.swing.JList<String> listaDisp;
    private javax.swing.JList<String> listaUser;
    // End of variables declaration//GEN-END:variables
}
